# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IDpW/b9N1Lk0N/buH5b0ap/lSVw0dh/3uDQllNZt5QRV+tTXPV+mbYiDvE09YJYfr6t/32DVvWCThAQO3R9Sfwdgr/kZMKWNhKkPXtv29/5ky4CEHYZfbTtDuwYEddxxLgNIQ26zuXsqAp9lHz6ChNbzKTKsIrXw1CU8jLP093yr7Z7SzrvCEy7RoMH2MRIhdEKunkb7EB4GawRT8Q0ps3nhIU7V6/KVs0rqdCm4PSEVT2G1pPhxj2J5Z1CK+470Kp99jHkiwpTHvOn3vUbR3JydaNLIcDqNtW40PTbegEqNNmkwUsPiwG7simPDrsSFLN6bA9wnWL3v4O+zPWEH7sDyQQqjV0+K6cZcG0CIJT25mbHSLTC0CNkjOA1p+nheGRXCQ7z0hmolY4A+F0axzOq/OOb/DgcXI2RX1yY4rESS+MLo8EZoCdPImQUJO3Vm4Hck3eir7tRQUXYf1xbnimqlNVqXQWsoOcryb3sYBAjhIAB/sfmZsZK+wKw1nPd2GWdXdi0Ix9aFzHp4globwJiWh8AV3weX2oXMZRfL7iwP8+2kDR/9LkHR1U6QT4acmNYG5Kps57BKCG83ZiULNjdPLk+7PxCzbY/2Ber43pboj9vfY6Z5/7zHDVfKzv/UnB2MJwi8INY1hje5Oy+iaony8XySMbbr8oI35/ignM4="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
