travis:
  secure:
    BINSTAR_TOKEN: IDpW/b9N1Lk0N/buH5b0ap/lSVw0dh/3uDQllNZt5QRV+tTXPV+mbYiDvE09YJYfr6t/32DVvWCThAQO3R9Sfwdgr/kZMKWNhKkPXtv29/5ky4CEHYZfbTtDuwYEddxxLgNIQ26zuXsqAp9lHz6ChNbzKTKsIrXw1CU8jLP093yr7Z7SzrvCEy7RoMH2MRIhdEKunkb7EB4GawRT8Q0ps3nhIU7V6/KVs0rqdCm4PSEVT2G1pPhxj2J5Z1CK+470Kp99jHkiwpTHvOn3vUbR3JydaNLIcDqNtW40PTbegEqNNmkwUsPiwG7simPDrsSFLN6bA9wnWL3v4O+zPWEH7sDyQQqjV0+K6cZcG0CIJT25mbHSLTC0CNkjOA1p+nheGRXCQ7z0hmolY4A+F0axzOq/OOb/DgcXI2RX1yY4rESS+MLo8EZoCdPImQUJO3Vm4Hck3eir7tRQUXYf1xbnimqlNVqXQWsoOcryb3sYBAjhIAB/sfmZsZK+wKw1nPd2GWdXdi0Ix9aFzHp4globwJiWh8AV3weX2oXMZRfL7iwP8+2kDR/9LkHR1U6QT4acmNYG5Kps57BKCG83ZiULNjdPLk+7PxCzbY/2Ber43pboj9vfY6Z5/7zHDVfKzv/UnB2MJwi8INY1hje5Oy+iaony8XySMbbr8oI35/ignM4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
